# An example configuration for benchmarking Momento ObjectStore over the
# HTTP/2 API. This exercises GET, PUT, and DELETE operations against a
# Momento object store.

[general]
# specify the protocol to be used
protocol = "momento_objectstore"
# the interval for stats integration and reporting
interval = 1
# the number of intervals to run the test for
duration = 30
# run the admin thread with a HTTP listener at the address provided, this allows
# stats exposition via HTTP
admin = "127.0.0.1:9090"
# optionally, set an initial seed for the PRNGs used to generate the workload.
# The default is to intialize from the OS entropy pool.
initial_seed = "0"

#[metrics]
# output file for detailed stats during the run
#output = "stats.json"
# format of the output file (possible values are json, msgpack, parquet)
#format = "json"
# optionally specify batch size for parquet row groups
# only valid for parquet output
#batch_size = 100_000
# optionally specify histogram type (can be standard (default) or sparse)
# only valid for parquet output
#histogram = "sparse"
# optionally, specify the sampling interval for metrics. Input is a string
# with the unit attached; for example "100ms" or "1s". Defaults to 1s.
#interval = "1s"

[debug]
# choose from: error, warn, info, debug, trace
log_level = "info"
# optionally, log to the file below instead of standard out
# log_file = "rpc-perf.log"
# backup file name for use with log rotation
log_backup = "rpc-perf.log.old"
# trigger log rotation when the file grows beyond this size (in bytes). Set this
# option to '0' to disable log rotation.
log_max_size = 1073741824

[target]
# specify the Momento HTTP ObjectStore API Endpoint
endpoints = ["https://api.objectstore.cell-4-us-west-2-1.prod.a.momentohq.com"]
# specify the name of the target object store
object_store_name = "test"

[storage]
# number of threads used to drive requests
threads = 4
# number of HTTP/2 connections per endpoint
poolsize = 4
# number of concurrent H2 streams per connection
concurrency = 128
# request timeout in milliseconds
request_timeout = 1000

[workload]
# the number of threads that will be used to generate the workload
threads = 1

[workload.ratelimit]
# set a global ratelimit for the workload
start = 50

[[workload.stores]]
# object name length, in bytes
klen = 32
# sets the number of objects that will be generated
nkeys = 100
# sets the object size, in bytes
vlen = 128
# use random bytes for the values
vkind = "bytes"
# optionally, set a TTL for PUT operations (default is 1 hour)
ttl = "1h"
# controls what commands will be used
commands = [
	# get a value
	{ verb = "get", weight = 80 },
	# put a value
	{ verb = "put", weight = 19 },
	# delete a value
	{ verb = "delete", weight = 1 },
]
