# A configuration that can be used as a smoketest against a memcached instance.

[general]
protocol = "memcache"
interval = 60
duration = 300
metrics_output = "rpcperf.parquet"
metrics_format = "parquet"
admin = "127.0.0.1:9090"

[debug]
log_level = "info"
log_backup = "rpc-perf.log.old"
log_max_size = 1073741824

[target]
endpoints = [
	"127.0.0.1:11211",
]

[client]
threads = 4
poolsize = 20
connect_timeout = 10000
request_timeout = 1000

[workload]
threads = 1

[workload.ratelimit]
start = 10_000

[[workload.keyspace]]
weight = 1
klen = 32
nkeys = 1_000_000
vlen = 128
vkind = "bytes"
message_compression_ratio = 10.0
commands = [
	{ verb = "get", weight = 80 },
	{ verb = "set", weight = 20 },
	{ verb = "delete", weight = 0 },
]
